name: Detect secrets

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install detect-secrets
        run: |
          pip install "detect-secrets[gibberish]==1.5.0"
      - name: Run detect-secrets-hook using baseline
        run: |
          git ls-files -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline
